<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyInvoicingApp.Application\MyInvoicingApp.Application.csproj" />
    <ProjectReference Include="..\MyInvoicingApp.Domain\MyInvoicingApp.Domain.csproj" />
  </ItemGroup>

</Project>